apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-node-deployment
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a-node
  template:
    metadata:
      labels:
        app: a-node
    spec:
      containers:
        - name: a-node-container
          image: tim010/a-node:v1 # or your own image
          ports:
            - containerPort: 3000
